name: panganBOTpublish

on:
  schedule:
    - cron: '0,15,30,45 * * * *'  # once every 15 minutes

jobs:
  pangan-post:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Scrapping Data from HargaPangan.ID
        run: Rscript panganHarvest.R
